# Generated by Django 4.2.20 on 2025-04-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('under_maintenance', 'En mantenimiento'), ('cleaning', 'En limpieza')], default='available', max_length=20),
        ),
    ]
